### ISSUE TITLE
AttributeError: 'int' object has no attribute 'value'

### ISSUE THREAD

**Issue by sm4rtk1dz** [SafeBreach-Labs/SirepRAT#2]
Using the SirepRAT python throws an AttributeError:

```
Traceback (most recent call last):
  File "SirepRAT.py", line 52, in <module>
    from common.mappings import SIREP_COMMANDS, RESULT_TYPE_TO_RESULT
  File "/home/kali/HackTheWorld/boxes/omni/SirepRAT/common/mappings.py", line 66, in <module>
    ResultRecordType.HResult.value: results.HResultResult,
AttributeError: 'int' object has no attribute 'value'
```

**Comment by sm4rtk1dz** [comment]
## Solution
```
pip uninstall enum
pip install enum34
```

**Comment by xIceFox** [comment]
That helped me too, thanks. Why somebody calls this two libraries nearly the same 😂

**Comment by dorazouri** [comment]
@sm4rtk1dz SirepRAT v2 is now committed and supports python3, for better experience with Kali! See latest code and [release](https://github.com/SafeBreach-Labs/SirepRAT/releases/tag/v2.0.0).
